### ISSUE TITLE
Shiro新增anonymous配置不生效，并且导致原有的部分配置失效

### ISSUE THREAD

**Issue by flyfrank** [flyfrank/just-do-it#7]
# 一、背景介绍
在项目中，在访问资源文件时需要去除权限验证，后端服务使用Shiro进行权限验证，于是在anonymous下新添加了资源文件路径配置，新增配置后，请求响应仍提示需要权限；并且在新添加配置后原有匿名访问路径也提示需要权限。

# 二、问题分析
Shiro是根据filterChainDefinitionMap中的配置进行请求路径匹配，一旦路径匹配成功，将使用对应的过滤器去处理请求。
## ShiroConfiguration.java
```
    @Bean(name = SHIRO_FILTER_NAME)
    public ShiroFilterFactoryBean getShiroFilterFactoryBean(SecurityManager securityManager,
                                                            ShiroConfig config, ShiroService
                                                                    shiroService) {
        ShiroFilterFactoryBean shiroFilterFactoryBean = new ShiroFilterFactoryBean();
        shiroFilterFactoryBean.setSecurityManager(securityManager);
        shiroFilterFactoryBean.setLoginUrl(config.getLoginUrl());
        Map<String, Filter> filters = new LinkedHashMap<String, Filter>();
        filters.put("anonymous", new ShiroAnonymousFilter());
        filters.put("authcToken", createAuthFilter(shiroService, config));
        shiroFilterFactoryBean.setFilters(filters);
        shiroFilterFactoryBean.setFilterChainDefinitionMap(config.getFilterChainDefinitionMap());
        return shiroFilterFactoryBean;
    }
```
##  ShiroConfig.java
```
	public Map<String, String> getFilterChainDefinitionMap() {
		if (MapUtils.isEmpty(filters)) {
			return new HashMap<>();
		}
		Map<String, String> filterMap = new HashMap<>();
		for (String key: filters.keySet()) {
			String [] paths = filters.get(key);
			for (String path: paths) {
				filterMap.put(path, key);
			}
		}
		return filterMap;
	}
```
## Shiro配置文件
```
shiro:
  loginUrl: /login
  filters:
    anonymous:
      - /
      - /*.*
      - /assets/**
      - /frontkit/service/login
      - /frontkit/service/logout/**
      - /frontkit/service/loginCaptcha
      - /frontkit/service/overTimeUpdatePwd
      - /frontkit/service/publics/**
      - /frontkit/service/common/**
      - /frontkit/service/swagger.json
      - /frontkit/service/app/wechat/**
      - /frontkit/service/material/download/**
    authcToken:
      - /**
```
根据上面配置，我们发现在配置filterChainDefinitionMap时候，项目中使用的是HashMap，上述filters总个数为13。在没有新增配置之前，filters的总数为12，而HashMap的默认总量为16，加载因子为0.75，刚好可以容纳12个元素，而且authcToken的配置项刚好排在最后；但是新增一个配置后，Hash Map进行了扩容，遍历HashMap时和配置的顺序不一致，导致部分配置失效，新增配置后HashMap中元素顺序如下：
![filterMap](https://user-images.githubusercontent.com/26216473/113819353-c2e63280-97ab-11eb-96d6-508c92e46849.png)
根据上图所示，由于Shiro按照fiters的顺序进行匹配，authcToken后的配置都将会匹配到authcToken这个filter，所以需要权限验证。

# 三、总结
根据上面的分析，该问题是由于filterChainDefinitionMap 中配置顺序导致的，在ShiroFilterFactoryBean的构造方法中，filterChainDefinitionMap 使用LinkedHashMap来保证顺序的，如下：
## ShiroFilterFactoryBean.java
```
    public ShiroFilterFactoryBean() {
        this.filters = new LinkedHashMap<String, Filter>();
        this.filterChainDefinitionMap = new LinkedHashMap<String, String>(); //order matters!
    }
```
所以在配置filterChainDefinitionMap 时注意要使用LinkedHashMap保证有序。
